### ISSUE TITLE
is this supposed to be private?

### ISSUE THREAD

**Issue by pete911** [jayeola/impex-files#1]

**Comment by jayeola** [comment]
Hi,

I published a private gist. Why did you ask if this gist is private? Can
you see it?
John Maclean
MSc (DIC)

Enterprise Linux Systems Engineer

**Comment by pete911** [comment]
yeah, this whole repo - https://github.com/jayeola/impex-files is public, but looks like it contains some file that should not be public, so I just thought I will notify you

**Comment by jayeola** [comment]
Thanks!!
-------- Original message --------From: Peter Reisinger <notifications@github.com> Date: 12/11/2020  09:25  (GMT+00:00) To: jayeola/impex-files <impex-files@noreply.github.com> Cc: john maclean <jayeola@gmail.com>, Comment <comment@noreply.github.com> Subject: Re: [jayeola/impex-files] is this supposed to be private? (#1) 
yeah, this whole repo - https://github.com/jayeola/impex-files is public, but looks like it contains some file that should not be public, so I just thought I will notify you
